/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_lois_video_wsplayer_H264decode */

#ifndef _Included_cn_lois_video_wsplayer_H264decode
#define _Included_cn_lois_video_wsplayer_H264decode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_lois_video_wsplayer_H264decode
 * Method:    DecodeOneFrame
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_cn_lois_video_wsplayer_H264decode_DecodeOneFrame
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     cn_lois_video_wsplayer_H264decode
 * Method:    DecodeG726Audio
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_cn_lois_video_wsplayer_H264decode_DecodeG726Audio
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     cn_lois_video_wsplayer_H264decode
 * Method:    Initialize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_lois_video_wsplayer_H264decode_Initialize
  (JNIEnv *, jclass);

/*
 * Class:     cn_lois_video_wsplayer_H264decode
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_lois_video_wsplayer_H264decode_Destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
